version: "3"

services:
  cattleshed:
     build: ../cattleshed/docker
     command: /bin/bash
     volumes:
       - "cattleshed_workspace:/home/sbuilder/workspace"
     network_mode: "host"  

  stensalio:
     build: ../stensalio/docker
     volumes:
       - "stensalio_data:/data"
       - "stensalio_public_json:/var/www/public_json"
     network_mode: "host"  
     command: ["/usr/bin/wait-for-it.sh", "cattleshed:2012", "/bin/bash"]
     depends_on:
       - "cattleshed"

volumes:
  cattleshed_workspace:
  stensalio_data:
  stensalio_public_json:
