version: "3"

services:
  cattleshed:
     cap_drop: 
       - ALL
     cap_add:
       - SYS_ADMIN
       - SYS_CHROOT
       - MKNOD
       - NET_BIND_SERVICE
       - NET_ADMIN
       - SYS_RAWIO
       - SYS_MODULE
     build: ../cattleshed/docker
     command: /bin/bash
     volumes:
       - "cattleshed_workspace:/home/sbuilder/workspace"
       - "cattleshed_var_log:/var/log"
     network_mode: "host"
     tmpfs:
       - /tmp

  stensalio:
     build: ../stensalio/docker
     volumes:
       - "stensalio_data:/data"
       - "stensalio_public_json:/var/www/public_json"
       - "stensalio_var_log:/var/log"
     network_mode: "host"
     tmpfs:
       - /tmp
     command: ["/usr/bin/wait-for-it.sh", "cattleshed:2012", "/bin/bash"]
     depends_on:
       - "cattleshed"

volumes:
  cattleshed_workspace:
  cattleshed_var_log:
  stensalio_data:
  stensalio_public_json:
  stensalio_var_log:
